export const fonts = {
  sfProDisplay: {
    black: 'SF-Pro-Display-Black',
    blackItalic: 'SF-Pro-Display-BlackItalic',
    bold: 'SF-Pro-Display-Bold',
    boldItalic: 'SF-Pro-Display-BoldItalic',
    heavy: 'SF-Pro-Display-Heavy',
    heavyItalic: 'SF-Pro-Display-HeavyItalic',
    light: 'SF-Pro-Display-Light',
    lightItalic: 'SF-Pro-Display-LightItalic',
    medium: 'SF-Pro-Display-Medium',
    mediumItalic: 'SF-Pro-Display-MediumItalic',
    regular: 'SF-Pro-Display-Regular',
    regularItalic: 'SF-Pro-Display-RegularItalic',
    semiBold: 'SF-Pro-Display-Semibold',
    semiBoldItalic: 'SF-Pro-Display-SemiboldItalic',
    thin: 'SF-Pro-Display-Thin',
    thinItalic: 'SF-Pro-Display-ThinItalic',
    ultraLight: 'SF-Pro-Display-Ultralight',
    ultraLightItalic: 'SF-Pro-Display-UltralightItalic',
  },
  Akkurat: {
    bold: 'Akkurat-Bold',
    boldItalic: 'Akkurat-Bold-Italic',
    light: 'Akkurat-Light',
    lightItalic: 'Akkurat-Light-Italic',
    normal: 'Akkurat-Normal',
    normalItalic: 'Akkurat-Normal-Italic',
  },
};
