export const globalAction = {
  SET_LOADING: 'SET_LOADING',
  SET_PROFILE: 'SET_PROFILE',
  SET_PRODUCT: 'SET_PRODUCT',
  SET_PHOTO: 'SET_PHOTO',
  SET_HAS_PHOTO: 'SET_HAS_PHOTO',
  SET_PHOTO_DB: 'SET_PHOTO_DB',
  SET_MODAL_VISIBLE: 'SET_MODAL_VISIBLE'
};
