export const globalAction = {
  SET_LOADING: 'SET_LOADING',
  SET_PROFILE: 'SET_PROFILE',
  SET_PRODUCT: 'SET_PRODUCT',
  SET_PHOTO: 'SET_PHOTO',
  SET_HAS_PHOTO: 'SET_HAS_PHOTO',
  SET_PHOTO_DB: 'SET_PHOTO_DB',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SET_TYPE: 'SET_TYPE',
  SET_PROCEDURE: 'SET_PROCEDURE',
  SET_OUTPUT: 'SET_OUTPUT',
  SET_GRADE: 'SET_GRADE',
  SET_CONSUMER: 'SET_CONSUMER',
  SET_STORE: 'SET_STORE',
  SET_INTRO: 'SET_INTRO'
};
